export interface AIModel {
  id: string              // OpenRouter model ID
  name: string            // Display name
  provider: string        // Company
  providerColor: string   // Brand color hex
  tagline: string         // One-liner
  description: string     // What it's good for (2-3 sentences)
  strengths: string[]     // Bullet points
  costPer1MInput: number  // USD
  costPer1MOutput: number // USD
  contextWindow: string   // e.g. "200K tokens"
  intelligenceRating: number  // 1-10
  speedRating: number         // 1-10 (10=fastest)
  badge?: string          // e.g. "Best Value", "Most Powerful", "Fastest"
  badgeColor?: string
  isDefault?: boolean
}

export const MODELS: AIModel[] = [
  {
    id: 'anthropic/claude-sonnet-4-5',
    name: 'Claude Sonnet',
    provider: 'Anthropic',
    providerColor: '#D97706',
    tagline: 'The sharpest thinker in the room',
    description: 'Anthropic\'s flagship model. Exceptional at complex reasoning, nuanced writing, coding, and analysis. The go-to for anything that requires real thinking.',
    strengths: ['Complex reasoning', 'Long-form writing', 'Code review & debugging', 'Research & analysis'],
    costPer1MInput: 3.00,
    costPer1MOutput: 15.00,
    contextWindow: '200K tokens',
    intelligenceRating: 9.5,
    speedRating: 7,
    badge: 'Best All-Rounder',
    badgeColor: '#D97706',
  },
  {
    id: 'anthropic/claude-haiku-4-5',
    name: 'Claude Haiku',
    provider: 'Anthropic',
    providerColor: '#D97706',
    tagline: 'Fast, cheap, surprisingly capable',
    description: 'Anthropic\'s fastest model. Handles most everyday tasks at a fraction of the cost. Great for quick answers, summarization, and simple coding tasks.',
    strengths: ['Quick Q&A', 'Summarization', 'Simple coding', 'High-volume tasks'],
    costPer1MInput: 0.80,
    costPer1MOutput: 4.00,
    contextWindow: '200K tokens',
    intelligenceRating: 7.5,
    speedRating: 9.5,
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    providerColor: '#10A37F',
    tagline: 'The world\'s most recognized AI',
    description: 'OpenAI\'s flagship multimodal model. Excellent at following complex instructions, structured output, and image understanding. Battle-tested by millions.',
    strengths: ['Instruction following', 'Structured output (JSON)', 'Image analysis', 'Tool use'],
    costPer1MInput: 2.50,
    costPer1MOutput: 10.00,
    contextWindow: '128K tokens',
    intelligenceRating: 9.0,
    speedRating: 7.5,
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    providerColor: '#10A37F',
    tagline: 'GPT-4 quality at budget price',
    description: 'OpenAI\'s efficient model — 94% of GPT-4o intelligence at a fraction of the cost. Perfect for most everyday tasks where you want OpenAI quality without the bill.',
    strengths: ['Everyday tasks', 'Content generation', 'Customer support', 'Fast responses'],
    costPer1MInput: 0.15,
    costPer1MOutput: 0.60,
    contextWindow: '128K tokens',
    intelligenceRating: 7.8,
    speedRating: 9,
    badge: 'Best Value (OpenAI)',
    badgeColor: '#10A37F',
  },
  {
    id: 'x-ai/grok-2-1212',
    name: 'Grok 2',
    provider: 'xAI',
    providerColor: '#1DA1F2',
    tagline: 'Real-time web access + no-filter answers',
    description: 'Elon Musk\'s xAI model. Has real-time web search built in and is known for direct, uncensored answers. Great for current events, trending topics, and honest feedback.',
    strengths: ['Real-time web search', 'Current events', 'Honest/direct answers', 'Twitter/X content'],
    costPer1MInput: 2.00,
    costPer1MOutput: 10.00,
    contextWindow: '131K tokens',
    intelligenceRating: 8.5,
    speedRating: 7,
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    providerColor: '#4F46E5',
    tagline: 'GPT-4 level at pennies per query',
    description: 'China\'s breakthrough model that shocked the AI world. Matches GPT-4o on most benchmarks at 10x lower cost. Especially strong at coding and math.',
    strengths: ['Code generation', 'Math & logic', 'Extremely cheap', 'Strong reasoning'],
    costPer1MInput: 0.27,
    costPer1MOutput: 1.10,
    contextWindow: '64K tokens',
    intelligenceRating: 8.8,
    speedRating: 8,
    badge: 'Best Value Overall',
    badgeColor: '#4F46E5',
    isDefault: true,
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    providerColor: '#4F46E5',
    tagline: 'Think before you answer — like o1 but free',
    description: 'DeepSeek\'s reasoning model. Like OpenAI\'s o1 — it thinks step by step before answering. Crushes math, science, and logic problems. Shockingly cheap for what it does.',
    strengths: ['Advanced math', 'Scientific reasoning', 'Step-by-step problem solving', 'Logic puzzles'],
    costPer1MInput: 0.55,
    costPer1MOutput: 2.19,
    contextWindow: '64K tokens',
    intelligenceRating: 9.2,
    speedRating: 5,
    badge: 'Best Reasoning',
    badgeColor: '#7C3AED',
  },
  {
    id: 'google/gemini-pro-1.5',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    providerColor: '#4285F4',
    tagline: 'Longest memory of any AI model',
    description: 'Google\'s powerhouse with a 2 million token context window — that\'s entire codebases, books, or massive datasets in one shot. Strong at multimodal tasks with Google\'s backing.',
    strengths: ['Massive context (2M tokens)', 'Document analysis', 'Multimodal', 'Long conversations'],
    costPer1MInput: 1.25,
    costPer1MOutput: 5.00,
    contextWindow: '2M tokens',
    intelligenceRating: 8.7,
    speedRating: 6.5,
    badge: 'Longest Context',
    badgeColor: '#4285F4',
  },
  {
    id: 'google/gemini-flash-1.5',
    name: 'Gemini Flash',
    provider: 'Google',
    providerColor: '#4285F4',
    tagline: 'Google speed at Google scale pricing',
    description: 'Google\'s fastest model. Multimodal capable (text, images, audio, video). Incredibly fast response times with solid quality. Best for high-volume, time-sensitive tasks.',
    strengths: ['Ultra-fast responses', 'Multimodal input', 'High volume tasks', 'Low latency'],
    costPer1MInput: 0.075,
    costPer1MOutput: 0.30,
    contextWindow: '1M tokens',
    intelligenceRating: 7.2,
    speedRating: 10,
    badge: 'Fastest',
    badgeColor: '#0EA5E9',
  },
  {
    id: 'mistralai/mistral-large',
    name: 'Mistral Large',
    provider: 'Mistral AI',
    providerColor: '#FF7000',
    tagline: 'European AI — privacy-first, multilingual',
    description: 'France\'s best AI. GDPR-compliant, data stays in Europe, strong multilingual support (especially French, Spanish, German, Italian). Great for business users with privacy requirements.',
    strengths: ['Privacy-focused', 'Multilingual', 'European compliance', 'Business writing'],
    costPer1MInput: 2.00,
    costPer1MOutput: 6.00,
    contextWindow: '128K tokens',
    intelligenceRating: 8.3,
    speedRating: 7.5,
  },
]

export const DEFAULT_MODEL = MODELS.find(m => m.isDefault) ?? MODELS[0]
