export interface AIModel {
  id: string
  name: string
  provider: string
  providerColor: string
  tagline: string
  description: string
  strengths: string[]
  costPer1MInput: number
  costPer1MOutput: number
  contextWindow: string
  intelligenceRating: number  // 1-10
  speedRating: number         // 1-10 (10=fastest)
  badge?: string
  badgeColor?: string
  isDefault?: boolean
}

export const MODELS: AIModel[] = [
  // ── Anthropic ──────────────────────────────────────────────
  {
    id: 'anthropic/claude-sonnet-4-5',
    name: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    providerColor: '#D97706',
    tagline: 'The sharpest thinker in the room',
    description: 'Anthropic\'s flagship model. Exceptional at complex reasoning, nuanced writing, coding, and analysis. The go-to for anything that requires real thinking.',
    strengths: ['Complex reasoning', 'Long-form writing', 'Code review & debugging', 'Research & analysis'],
    costPer1MInput: 3.00,
    costPer1MOutput: 15.00,
    contextWindow: '200K tokens',
    intelligenceRating: 9.5,
    speedRating: 7,
    badge: 'Best All-Rounder',
    badgeColor: '#D97706',
  },
  {
    id: 'anthropic/claude-opus-4-5',
    name: 'Claude Opus 4.5',
    provider: 'Anthropic',
    providerColor: '#D97706',
    tagline: 'Maximum intelligence, no compromises',
    description: 'Anthropic\'s most powerful model. Tackles the hardest tasks with unmatched depth. Best for research, complex analysis, and multi-step reasoning where quality is everything.',
    strengths: ['Deep research', 'Multi-step reasoning', 'Complex code architecture', 'Expert-level analysis'],
    costPer1MInput: 15.00,
    costPer1MOutput: 75.00,
    contextWindow: '200K tokens',
    intelligenceRating: 10,
    speedRating: 4,
    badge: 'Most Powerful',
    badgeColor: '#B45309',
  },
  {
    id: 'anthropic/claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    providerColor: '#D97706',
    tagline: 'Fast, cheap, surprisingly capable',
    description: 'Anthropic\'s fastest model. Handles most everyday tasks at a fraction of the cost. Great for quick answers, summarization, and simple coding tasks.',
    strengths: ['Quick Q&A', 'Summarization', 'Simple coding', 'High-volume tasks'],
    costPer1MInput: 0.80,
    costPer1MOutput: 4.00,
    contextWindow: '200K tokens',
    intelligenceRating: 7.5,
    speedRating: 9.5,
  },
  // ── OpenAI ─────────────────────────────────────────────────
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    providerColor: '#10A37F',
    tagline: 'The world\'s most recognized AI',
    description: 'OpenAI\'s flagship multimodal model. Excellent at following complex instructions, structured output, and image understanding. Battle-tested by millions.',
    strengths: ['Instruction following', 'Structured output (JSON)', 'Image analysis', 'Tool use'],
    costPer1MInput: 2.50,
    costPer1MOutput: 10.00,
    contextWindow: '128K tokens',
    intelligenceRating: 9.0,
    speedRating: 7.5,
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    providerColor: '#10A37F',
    tagline: 'GPT-4 quality at budget price',
    description: 'OpenAI\'s efficient model — 94% of GPT-4o intelligence at a fraction of the cost. Perfect for most everyday tasks where you want OpenAI quality without the bill.',
    strengths: ['Everyday tasks', 'Content generation', 'Customer support', 'Fast responses'],
    costPer1MInput: 0.15,
    costPer1MOutput: 0.60,
    contextWindow: '128K tokens',
    intelligenceRating: 7.8,
    speedRating: 9,
    badge: 'Best Value (OpenAI)',
    badgeColor: '#10A37F',
  },
  {
    id: 'openai/o3-mini',
    name: 'o3 Mini',
    provider: 'OpenAI',
    providerColor: '#10A37F',
    tagline: 'OpenAI\'s reasoning model, made affordable',
    description: 'OpenAI\'s compact reasoning model. Thinks before it answers — great for math, logic, and coding challenges where accuracy matters more than speed.',
    strengths: ['Math & logic', 'Code debugging', 'Scientific reasoning', 'Step-by-step problems'],
    costPer1MInput: 1.10,
    costPer1MOutput: 4.40,
    contextWindow: '200K tokens',
    intelligenceRating: 9.2,
    speedRating: 6,
    badge: 'Best Reasoning (OpenAI)',
    badgeColor: '#059669',
  },
  // ── xAI ────────────────────────────────────────────────────
  {
    id: 'x-ai/grok-3',
    name: 'Grok 3',
    provider: 'xAI',
    providerColor: '#1DA1F2',
    tagline: 'xAI\'s most capable — real-time + raw',
    description: 'Elon\'s latest flagship. Real-time web access, huge context, and known for direct uncensored answers. Strong on current events, coding, and big-picture analysis.',
    strengths: ['Real-time web search', 'Current events', 'Direct answers', 'Long-form reasoning'],
    costPer1MInput: 3.00,
    costPer1MOutput: 15.00,
    contextWindow: '131K tokens',
    intelligenceRating: 9.3,
    speedRating: 6.5,
  },
  {
    id: 'x-ai/grok-3-mini',
    name: 'Grok 3 Mini',
    provider: 'xAI',
    providerColor: '#1DA1F2',
    tagline: 'Fast Grok at a fraction of the cost',
    description: 'Lightweight version of Grok 3. Retains the real-time web access and direct style but faster and cheaper. Great for quick lookups and social media content.',
    strengths: ['Fast responses', 'Real-time web', 'Social content', 'Budget-friendly'],
    costPer1MInput: 0.30,
    costPer1MOutput: 0.50,
    contextWindow: '131K tokens',
    intelligenceRating: 7.8,
    speedRating: 9,
    badge: 'Best Value (xAI)',
    badgeColor: '#1DA1F2',
  },
  // ── DeepSeek ───────────────────────────────────────────────
  {
    id: 'deepseek/deepseek-chat-v3-0324',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    providerColor: '#4F46E5',
    tagline: 'GPT-4 level at pennies per query',
    description: 'China\'s breakthrough model that shocked the AI world. Matches GPT-4o on most benchmarks at 10x lower cost. Especially strong at coding and math.',
    strengths: ['Code generation', 'Math & logic', 'Extremely cheap', 'Strong reasoning'],
    costPer1MInput: 0.27,
    costPer1MOutput: 1.10,
    contextWindow: '64K tokens',
    intelligenceRating: 8.8,
    speedRating: 8,
    badge: 'Best Value Overall',
    badgeColor: '#4F46E5',
    isDefault: true,
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    providerColor: '#4F46E5',
    tagline: 'Think before you answer — like o1 but cheap',
    description: 'DeepSeek\'s reasoning model. Like OpenAI\'s o1 — it thinks step by step before answering. Crushes math, science, and logic problems at a shocking price.',
    strengths: ['Advanced math', 'Scientific reasoning', 'Step-by-step logic', 'Cheap reasoning'],
    costPer1MInput: 0.55,
    costPer1MOutput: 2.19,
    contextWindow: '64K tokens',
    intelligenceRating: 9.2,
    speedRating: 5,
    badge: 'Best Reasoning (Budget)',
    badgeColor: '#7C3AED',
  },
  // ── Google ─────────────────────────────────────────────────
  {
    id: 'google/gemini-2.5-pro-preview',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    providerColor: '#4285F4',
    tagline: 'Google\'s smartest — with monster context',
    description: 'Google\'s latest flagship with a massive context window. Excellent at multimodal tasks, document analysis, and long conversations. Rivals the best from OpenAI and Anthropic.',
    strengths: ['Massive context', 'Multimodal (text/images)', 'Document analysis', 'Long conversations'],
    costPer1MInput: 1.25,
    costPer1MOutput: 10.00,
    contextWindow: '1M tokens',
    intelligenceRating: 9.4,
    speedRating: 6,
    badge: 'Longest Context',
    badgeColor: '#4285F4',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    providerColor: '#4285F4',
    tagline: 'Google speed at Google scale pricing',
    description: 'Google\'s fastest model. Multimodal capable (text, images, audio, video). Incredibly fast response times with solid quality. Best for high-volume, time-sensitive tasks.',
    strengths: ['Ultra-fast responses', 'Multimodal input', 'High volume tasks', 'Low latency'],
    costPer1MInput: 0.10,
    costPer1MOutput: 0.40,
    contextWindow: '1M tokens',
    intelligenceRating: 7.5,
    speedRating: 10,
    badge: 'Fastest',
    badgeColor: '#0EA5E9',
  },
  // ── Meta ───────────────────────────────────────────────────
  {
    id: 'meta-llama/llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta',
    providerColor: '#0866FF',
    tagline: 'Meta\'s newest — insanely cheap',
    description: 'Meta\'s latest flagship open model. Excellent performance at an incredibly low price. Great for coding, analysis, and anyone who wants strong AI without the bill.',
    strengths: ['Open source', 'Ultra-cheap', 'Coding & analysis', 'No data retention'],
    costPer1MInput: 0.15,
    costPer1MOutput: 0.60,
    contextWindow: '1M tokens',
    intelligenceRating: 8.5,
    speedRating: 8.5,
    badge: 'Best Open Source',
    badgeColor: '#0866FF',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    providerColor: '#0866FF',
    tagline: 'Proven open source workhorse',
    description: 'Meta\'s battle-tested open model. Solid across coding, writing, and analysis. A reliable choice when you want open-source quality at low cost.',
    strengths: ['Open source', 'Privacy-focused', 'Coding & analysis', 'No data retention'],
    costPer1MInput: 0.10,
    costPer1MOutput: 0.32,
    contextWindow: '128K tokens',
    intelligenceRating: 8.0,
    speedRating: 8,
  },
  // ── MiniMax ────────────────────────────────────────────────
  {
    id: 'minimax/minimax-m2.5',
    name: 'MiniMax M2.5',
    provider: 'MiniMax',
    providerColor: '#06B6D4',
    tagline: 'Cheapest quality AI on the market',
    description: 'MiniMax\'s latest model with an enormous 1M token context window at the lowest price of any quality model. Great for long documents, bulk processing, and budget-conscious users.',
    strengths: ['Ultra-cheap', 'Massive context (1M)', 'Bulk processing', 'Long documents'],
    costPer1MInput: 0.15,
    costPer1MOutput: 1.15,
    contextWindow: '1M tokens',
    intelligenceRating: 7.8,
    speedRating: 8,
    badge: 'Cheapest',
    badgeColor: '#06B6D4',
  },
  {
    id: 'minimax/minimax-m1',
    name: 'MiniMax M1',
    provider: 'MiniMax',
    providerColor: '#06B6D4',
    tagline: 'MiniMax flagship — reasoning + huge context',
    description: 'MiniMax\'s most capable model. Extended thinking mode, massive context window, and strong across coding, math, and long-form tasks. Surprisingly powerful for the price.',
    strengths: ['Extended thinking', 'Huge context', 'Math & coding', 'Long documents'],
    costPer1MInput: 0.40,
    costPer1MOutput: 2.20,
    contextWindow: '1M tokens',
    intelligenceRating: 8.8,
    speedRating: 6,
  },
  // ── Perplexity ─────────────────────────────────────────────
  {
    id: 'perplexity/sonar-pro',
    name: 'Perplexity Sonar Pro',
    provider: 'Perplexity',
    providerColor: '#20B2AA',
    tagline: 'Real-time web search built in',
    description: 'Perplexity\'s flagship search model. Every answer is grounded in live web results with citations. If you need current information, news, or factual lookups — this is the one.',
    strengths: ['Real-time web search', 'Cited sources', 'Current events', 'Fact-checking'],
    costPer1MInput: 3.00,
    costPer1MOutput: 15.00,
    contextWindow: '200K tokens',
    intelligenceRating: 8.5,
    speedRating: 7,
    badge: 'Best for Web Search',
    badgeColor: '#20B2AA',
  },
  // ── OpenAI Reasoning ───────────────────────────────────────
  {
    id: 'openai/o3',
    name: 'o3',
    provider: 'OpenAI',
    providerColor: '#10A37F',
    tagline: 'OpenAI\'s most powerful reasoning model',
    description: 'OpenAI\'s flagship reasoning model. Thinks deeply before answering — best for the hardest math, science, and logic problems where accuracy is everything. Worth the price for complex tasks.',
    strengths: ['Advanced math', 'Complex reasoning', 'Scientific analysis', 'Coding architecture'],
    costPer1MInput: 2.00,
    costPer1MOutput: 8.00,
    contextWindow: '200K tokens',
    intelligenceRating: 9.8,
    speedRating: 4,
    badge: 'Most Powerful (OpenAI)',
    badgeColor: '#059669',
  },
  // ── DeepSeek updated ───────────────────────────────────────
  {
    id: 'deepseek/deepseek-r1-0528',
    name: 'DeepSeek R1 (May \'28)',
    provider: 'DeepSeek',
    providerColor: '#4F46E5',
    tagline: 'Updated reasoning model — better than ever',
    description: 'The latest updated version of DeepSeek R1, released May 2025. Improved reasoning accuracy over the original. Same incredible price — still beats GPT-o1 on most benchmarks at a fraction of the cost.',
    strengths: ['Advanced reasoning', 'Math & science', 'Improved accuracy', 'Cheap reasoning'],
    costPer1MInput: 0.50,
    costPer1MOutput: 2.15,
    contextWindow: '64K tokens',
    intelligenceRating: 9.4,
    speedRating: 5,
  },
  // ── Mistral ────────────────────────────────────────────────
  {
    id: 'mistralai/mistral-large-2512',
    name: 'Mistral Large',
    provider: 'Mistral AI',
    providerColor: '#FF7000',
    tagline: 'European AI — privacy-first, multilingual',
    description: 'France\'s best AI. GDPR-compliant, data stays in Europe, strong multilingual support. Great for business users with privacy requirements.',
    strengths: ['Privacy-focused', 'Multilingual', 'European compliance', 'Business writing'],
    costPer1MInput: 0.50,
    costPer1MOutput: 1.50,
    contextWindow: '128K tokens',
    intelligenceRating: 8.3,
    speedRating: 7.5,
  },
]

export const DEFAULT_MODEL = MODELS.find(m => m.isDefault) ?? MODELS[0]
